name: .NET Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, dev ]
  workflow_dispatch:

jobs:
  build-net6:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build solution
      run: dotnet build --no-restore
    - name: Exclude analyzers from tests
      run: dotnet sln remove ../Analyzers/**
    - name: Run tests
      run: dotnet test --no-restore --verbosity normal
